10 create rest routes on server for all required features
Danilo-Danijel-team/sms_sender pull request #38
Opened 2022-08-28 17:47 UTC by danilojezernik

<img src="https://img.devrant.com/devrant/rant/r_2880659_Vum14.jpg" height="250"></img>

*List linked issues related to this pull request.*
#10

2022-08-29 16:37 UTC, ethernal12 commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(error404(err.response.status, err.response.statusText));
In my commit no. 579165c I added the sending of true value when msg is not found instead of an error, so in case we don`t send the msg the tests pass regardless.  Can you add back this functionality. 
![msg_delete](https://user-images.githubusercontent.com/31479093/187249876-998754e0-f9d4-401a-b929-1073c7c49a10.png)

2022-08-30 05:42 UTC, danilojezernik commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(error404(err.response.status, err.response.statusText));
Cahanges were made and commit is made.

2022-09-18 19:09 UTC, danilojezernik commented
@urosjarc @ethernal12 : Ravnokar sem commital vse spremembe v ta pull.

@ethernal12 : Preveri in javi, če je vse ok.

2022-09-18 19:51 UTC, ethernal12 commented
Ok.

V ned., 18. sep. 2022 21:09 je oseba Danilo ***@***.***>
napisala:

> @urosjarc <https://github.com/urosjarc> @ethernal12
> <https://github.com/ethernal12> : Ravnokar sem commital vse spremembe v
> ta pull.
>
> @ethernal12 <https://github.com/ethernal12> : Preveri in javi, če je vse
> ok.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Danilo-Danijel-team/sms_sender/pull/38#issuecomment-1250368714>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHQFKNLUFLS6COZHQQE52YTV65SHXANCNFSM573NVOBA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-19 01:33 UTC, urosjarc commented
@danilojezernik Sprejeto!

2022-09-20 21:00 UTC, urosjarc requested changes
@danilojezernik, @ethernal12 Pogledal sem kodo in manjka najpomembnejša stvar... Service ki preverja na vsake 15 min ali je potrebno poslati sms. Tole se v ta pull request ne bo dodajalo saj bom ustvaril nov issue in se bo to na svojem branchu delalo.

V kodi nisem najdel nič kaj takega kar bi bilo problematično, je pa treba pogledati če se res vse knjižnice v package.json uporablja, nekatere so mi sumljive.

Manjka pa veliko res.error v kodi.
Na splošno pa nimam z pull requestom nobenih težav.

2022-09-22 19:45 UTC, danilojezernik commented on api/src/app.js
> +app.use((req, res, next) => {
initialized and session sem pustil v app.js, kot tudi rout auth, ostalo pa sem premaknil v middleware in logiko sedaj črpa iz middleware.js. Je ok... sem spremembe commital.

2022-09-22 19:46 UTC, danilojezernik commented on api/src/app.js
Zadeva urejena, težava pa je, kako zadevo prekiniti. Bota to clearInterval pogledala z Korbiju jutri. Ker nevem kako si mislil.

2022-09-22 20:01 UTC, danilojezernik commented on api/src/routes/auth.js
> +  res.json({ msg: message, error: 403 });
Ne res.error se ne uporablja, ker mi pošilja težavo, da error ni funkcija. Sem zato zadevo sicer malo uredil, da bo vračalo kot mora. Poiljam kodo:

router.get('/login', (req, res, next) => {
  const message = 'Check your password and username and try again!';
  if (req.user) {
    next();
  } else {
    res.status(403).json({ message });
  }
});

je ok?

2022-09-22 20:11 UTC, danilojezernik commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
Če tukaj uporabim ` res.error` mi vrača neko čudno napako. Kaj pa tebi @ethernal12 ?

2022-09-22 20:15 UTC, danilojezernik commented on api/.env_replaceme
> -DEBUG="express:application"
Sem ustvaril file v api direktoriju `.env_replaceme` in vnesel napisano. Zanima me, ali se to sedaj zamenja z .env ali se tako pusti, da boš ti to uporabil in vnašal, ko boš konfiguriral?

2022-09-22 22:02 UTC, urosjarc commented on api/src/app.js
@danilojezernik Ko ustvariš interval shraniš id intervala v exports.intervalID katerega potem uporabiš v clear. Zmenjeno bova z @ethernal12 pogledala.

2022-09-22 22:03 UTC, urosjarc commented on api/src/app.js
> +app.use((req, res, next) => {
@danilojezernik Super tako je app.js res čist kakršne koli logike. Super!

2022-09-22 22:05 UTC, urosjarc commented on api/.env_replaceme
> -DEBUG="express:application"
@danilojezernik .env_replace me se comita v github da lahko nekdo ki projekt klonira takoj zamenja na lokalnem direktoriju .env_replaceme z .env in nastavi svojo konfiguracijo. Točno tako!

2022-09-22 22:06 UTC, urosjarc commented on api/.env_replaceme
> -DEBUG="express:application"
@danilojezernik Samo mislim da si pozabil commitat ker ga v repotu še vedno ne vidim.

2022-09-22 22:10 UTC, urosjarc commented on api/src/app.js
@danilojezernik Pa pozabil si da sva naredila poseben issue ki je namenjen posebej za sms sender. Ta pull request je prevelik da bi še to notri dalo, se ne bomo nič znajdel v morju failov. Ta feature je tako pomemben da ga bomo delal na posebnem pull requestu (branchu). Prestavi faile ki si jih naredil za sms sender v tisti branch.

2022-09-22 22:11 UTC, urosjarc commented on api/src/app.js
```javascript
exports.intervalID = null;

exports.start = () -> {
      exports.intervalID = setInterval(...)
}
```

Tako ga shraniš.

2022-09-22 22:16 UTC, urosjarc commented on api/src/routes/auth.js
> +  res.json({ msg: message, error: 403 });
To lahko uporabiš kar res.error saj gre za uporabniško napako... Kar koli kar ni med 200 in 399 statusom se šteje za napako.

2022-09-22 22:17 UTC, urosjarc commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
@danilojezernik Če vrača čudno napako je potrebno to raziskati. Kaj pa ti napiše oziroma vrača?

2022-09-22 22:43 UTC, danilojezernik commented on api/src/app.js
@urosjarc Midva sva se sicer zadeve malo drugače lotila. Takoj ko se server požene se inicializira pošiljanje smsov:

```javascript
// INIT ALL SERVERICES
twilioApi.init();
calendarApi.init();
// SMS SENDING INTERVAL 15min
smsSender.init();
```

v smsSender.js:
```javascript
exports.init = () => setInterval(() => {
  api.createMsg(twilioProd.fromNumber, '+38640664247', 'heyoooooo');
}, 15 * 60 * 1000);
```

Ampak problem je bil, kako poklicati konec intervala... preko routa,... ker edini način, da @ethernal12 ni več prejemal smsjev je, da sem `init` zakomentiral, da se ni vsakih x minut sms poslav.

2022-09-23 03:42 UTC, urosjarc commented on api/src/app.js
Dobro si poglej tole: https://developer.mozilla.org/en-US/docs/Web/API/setInterval

```
exports.intervalID = null;

exports.start = () -> {
      exports.intervalID = setInterval(...)
}
exports.stop = () -> {
      clearInterval(exports.intervalID);
}
```

2022-09-23 03:44 UTC, urosjarc commented on api/src/app.js
@danilojezernik, @ethernal12  Vidva nista shranila to kar setInterval vrača in ga zaradi tega nista mogla kenslat.

2022-09-23 06:44 UTC, danilojezernik commented on api/src/app.js
@urosjarc : Aja, ti si boš potem testing naredu preko nekega 'frontenda'? Ker sem razumel, da takoj ko se server vklopi, se smsi začnejo pošiljat.

2022-09-23 11:40 UTC, urosjarc commented on api/src/app.js
@danilojezernik Glede testinga te nisem razumel... Server ima vse funkcijonalnosti naštimane tako da dela vse brez frontenda, frontend je samo dashboard da vidiš kaj se na serverju dogaja in za dodatne informacije. Sms se ne bodo pošiljali preko frontenda ker sej je logično, pomisli da imaš frontend za android, desktop, web... Kdo bo pošiljal sms-e ... Server mora skrbeti, frontendi pa samo prikazujejo kaj se na serverju dogaja.

2022-09-23 11:45 UTC, urosjarc commented on api/src/app.js
@danilojezernik No popravek sms se bodo lahko manualno pošiljali preko frontenda preko dostopa do rauta na serverju. Vendar avtomatski sms bodo leteli preko backenda.

2022-09-23 12:11 UTC, ethernal12 commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
@danilojezernik Bom danes pogledau , ti sporočim...

2022-09-23 13:25 UTC, danilojezernik commented on api/src/app.js
@urosjarc Ajaaaaa... ti bi pač route ustvaru, preko katerega lahko kličeš oziroma začneš interval in potem preko routa kličeš stop interval (pač lahk zadevo štartaš v Postmanu). Js sm pa mislu, da hočeš, da se zadeva zalavfa takoj sama od sebe, ko ti štartaš server in potem nekako to prekineš :D... To se pa lahko naredi ja... sta to zadevo že zrihtala, al jo midva danes oziroma ta teden?

2022-09-23 14:57 UTC, urosjarc commented on api/src/app.js
@danilojezernik Interval se zacne z zacetkom serverja automatsko, stop in start route pa bo za testiranje.

2022-09-23 19:14 UTC, danilojezernik commented on api/src/app.js
@urosjarc nadaljujem pogovor v branchu #40 ... commital sem spremembe...

2022-09-23 23:29 UTC, urosjarc commented on api/src/app.js
@danilojezernik @ethernal12 Ok tale pull request čaka samo še res.error analizo od @ethernal12 ter potrebno je še smsSender.js iz tega brancha odstraniti in prestaviti v #40 da ne bo razsparcelirane kode po pull requestih.

Še to se naredi potem pa mergam v master.

2022-09-25 14:49 UTC, ethernal12 commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
@danilojezernik @urosjarc Sem popravil na error(statusText, status.code) v msg in calendar routih in comitau, meni vrača vse errorje kot mora.

2022-09-25 15:15 UTC, urosjarc approved these changes
Ok, za prvi projekt bo tole več kot dovolj.

2022-09-25 15:19 UTC, urosjarc commented on api/src/routes/msg.js
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
@ethernal12 Tole še vedno ni popravljeno!

2022-09-25 15:28 UTC, urosjarc commented
@danilojezernik, @ethernal12 res.statusov(4xx) je po celem projektu še vedno veliko in bi jih bilo fino zamenjat z res.error vendar dobro ne bom težil. Čeprav mi OCD buta ven 🤣 

<img src="https://thumbs.gfycat.com/OblongUnequaledLangur-max-1mb.gif">

2022-09-25 15:33 UTC, urosjarc commented
@ethernal12: @danilojezernik  Te je dodal kot review/erja moraš potrditi tudi ti da se strinjaš z pull requestom, potem lahko jaz mergam ko boš potrdil. Overridat pa ne moram.

2022-09-25 15:34 UTC, ethernal12 commented
Sm pullou zadnji commit in pri meni zgleda vse popravljeno ... Tudi v
svojem commitu gledam in vidim, da sem popravil 🤔

V V ned., 25. sep. 2022 ob 17:19 je oseba Uroš Jarc <
***@***.***> napisala:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In api/src/routes/msg.js
> <https://github.com/Danilo-Danijel-team/sms_sender/pull/38#discussion_r979420503>
> :
>
> > +  api.getBySID(requestedSid).then((response) => {
>
> +    if (!requestedSid) return res.error(`SMS by SID:${requestedSid} not found`, 404);
>
> +    logHistory(`GET SMS BY SID:${requestedSid} was initialized`, `${req.originalUrl}`);
>
> +    res.json(response.data);
>
> +  }).catch((err) => {
>
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
>
> +  });
>
> +});
>
> +
>
> +/* POST NEW SMS. */
>
> +router.post('/', (req, res) => {
>
> +  api.createMsg(twilioProd.fromNumber, '+38640664247', 'heyoooooo').then((response) => {
>
> +    logHistory('POST NEW SMS was initialized', `${req.originalUrl}`);
>
> +    res.json(response.data);
>
> +  }).catch((err) => {
>
> +    res.status(err.response.status).send(errorThrow(err.response.status, err.response.statusText));
>
>
> @ethernal12 <https://github.com/ethernal12> Tole še vedno ni popravljeno!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Danilo-Danijel-team/sms_sender/pull/38#discussion_r979420503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHQFKNPNP6JWIAOY2KAADCLWABUO7ANCNFSM573NVOBA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-26 01:08 UTC, urosjarc commented
@ethernal12 O pa res gledal sem staro verzijo, github mi ni hotel prikazati sprememb na review-ju

2022-09-26 23:24 UTC, urosjarc commented
@ethernal12 Prosim potrdi review ker ne moram mergat brez tvojega aprovala.

2022-09-26 23:26 UTC, urosjarc approved these changes

2022-09-26 23:27 UTC, urosjarc approved these changes

2022-09-26 23:30 UTC, merged

2022-09-26 23:31 UTC, urosjarc commented
@ethernal12 @danilojezernik Pull request mergan! Posodobita svoje branche.